spring:
  application:
    name: certificate-blockchain-api

  datasource:
    url: jdbc:postgresql://ep-quiet-bush-a1dj8gts-pooler.ap-southeast-1.aws.neon.tech/cetification?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_MXDopVtUy7G5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

blockchain:
  rpc-url: http://localhost:8548
  chain-id: 1337
  contract-address: "0x2E1f232a9439C3D459FcEca0BeEf13acc8259Dd8"
  admin-private-key: "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63"
  issuer-name: "Tr??ng ??i h?c Công nghi?p thành ph? H? Chí Minh"

logging:
  level:
    root: INFO
    com.certificate.blockchain: DEBUG
    org.web3j: DEBUG